import { StyleSheet } from 'react-native';
import GlobalStyles, { colors } from './GlobalStyles';

const CartScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    paddingHorizontal: 0,
  },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  // Header
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 24,
    paddingBottom: 12,
    backgroundColor: colors.secondary,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.textPrimary,
    textAlign: 'center',
  },
  // Section Title
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.textPrimary,
    marginTop: 18,
    marginBottom: 8,
    marginLeft: 16,
  },
  // Address
  addressRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginHorizontal: 16,
    marginBottom: 12,
  },
  addressCard: {
    flex: 1,
    backgroundColor: '#fafafa',
    borderRadius: 18,
    padding: 18,
    marginRight: 12,
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 6,
    minWidth: 170,
    maxWidth: 210,
    position: 'relative',
    marginBottom: 8,
    height: 80,
    justifyContent: 'center',
    overflow: 'hidden',
  },
  addressTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 2,
  },
  addressActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  addressLabel: {
    fontWeight: 'bold',
    color: colors.primary,
    fontSize: 13,
  },
  addressText: {
    color: colors.textSecondary,
    fontSize: 12,
    marginBottom: 1,
    lineHeight: 16,
  },
  editIcon: {
    padding: 4,
    backgroundColor: colors.lightGray,
    borderRadius: 16,
    zIndex: 2,
    marginLeft: 0,
  },
  trashIcon: {
    padding: 4,
    backgroundColor: colors.lightGray,
    borderRadius: 16,
    zIndex: 2,
    marginLeft: 6,
  },
  addAddressCard: {
    width: 44,
    height: 44,
    backgroundColor: colors.lightGray,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: colors.primary,
    borderStyle: 'dashed',
    marginRight: 8,
    marginBottom: 4,
  },
  // Product Card
  productCard: {
    flexDirection: 'row',
    backgroundColor: colors.card,
    borderRadius: 12,
    marginHorizontal: 16,
    marginBottom: 14,
    padding: 10,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
    alignItems: 'center',
  },
  productImage: {
    width: 80,
    height: 80,
    borderRadius: 10,
    marginRight: 12,
    backgroundColor: colors.lightGray,
  },
  productInfo: {
    flex: 1,
    justifyContent: 'center',
  },
  variationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
    flexWrap: 'wrap',
  },
  productVariationLabel: {
    fontSize: 14,
    color: colors.textPrimary,
    fontWeight: '500',
    marginRight: 6,
  },
  variationTag: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 2,
    marginRight: 6,
    marginBottom: 2,
    backgroundColor: colors.secondary,
  },
  variationTagText: {
    fontSize: 13,
    color: colors.textPrimary,
  },
  priceRowBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.lightGray,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginTop: 6,
    marginBottom: 2,
  },
  productName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.textPrimary,
    marginBottom: 2,
  },
  productVariation: {
    fontSize: 13,
    color: colors.textSecondary,
    marginBottom: 2,
  },
  productRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 2,
  },
  productRating: {
    fontSize: 14,
    color: colors.textPrimary,
    marginRight: 2,
    fontWeight: 'bold',
  },
  productPriceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 2,
  },
  productPrice: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.primary,
    marginRight: 8,
  },
  productDiscount: {
    fontSize: 12,
    color: colors.primary,
    fontWeight: 'bold',
    marginRight: 8,
  },
  productOldPrice: {
    fontSize: 12,
    color: colors.textMuted,
    textDecorationLine: 'line-through',
  },
  productCheckBox: {
    marginLeft: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  // Order Summary
  orderSummaryCard: {
    backgroundColor: colors.card,
    borderRadius: 12,
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 24,
    padding: 16,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  orderSummaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  orderSummaryLabel: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.textPrimary,
  },
  orderSummaryAmount: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.primary,
  },
  fixedPayButtonContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 16,
    paddingBottom: 16,
    backgroundColor: 'rgba(255,255,255,0.95)',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 8,
    zIndex: 10,
    alignItems: 'center',
  },
  payButton: {
    ...GlobalStyles.button,
    backgroundColor: colors.primary,
    paddingVertical: 7,
    borderRadius: 10,
    marginBottom: 0,
    width: '60%',
    maxWidth: 500,
  },
  payButtonDisabled: {
    backgroundColor: colors.mediumGray,
  },
  payButtonText: {
    ...GlobalStyles.buttonText,
    textAlign: 'center',
    fontSize: 14,
  },
  emptyText: {
    ...GlobalStyles.bodyText,
    fontSize: 18,
    color: colors.textMuted,
    textAlign: 'center',
    marginTop: 32,
  },
  fixedActionBarContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingBottom: 10,
    paddingTop: 10,
    backgroundColor: 'rgba(255,255,255,0.98)',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 8,
    zIndex: 20,
  },
  actionBarLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  actionBarRight: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    flex: 1.2,
  },
  actionBarText: {
    fontSize: 15,
    color: colors.textPrimary,
    marginLeft: 2,
    marginRight: 2,
  },
  actionBarTotal: {
    fontSize: 16,
    fontWeight: 'bold',
    marginRight: 16,
    color: colors.textPrimary,
  },
  stickyHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 10,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    zIndex: 30,
  },
  cartItemRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: colors.card,
    borderRadius: 12,
    marginHorizontal: 16,
    marginBottom: 14,
    padding: 10,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  cartItemImage: {
    width: 80,
    height: 80,
    borderRadius: 10,
    marginRight: 10,
    backgroundColor: colors.lightGray,
  },
  cartItemInfo: {
    flex: 1,
    justifyContent: 'center',
  },
  cartItemName: {
    fontSize: 15,
    fontWeight: 'bold',
    color: colors.textPrimary,
    marginBottom: 2,
  },
  cartItemVariationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 2,
  },
  cartItemPicker: {
    flex: 1,
    height: 28,
    marginLeft: -8,
    marginRight: 8,
    color: colors.textPrimary,
    fontSize: 13,
  },
  cartItemPriceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 2,
    marginBottom: 2,
  },
  cartItemPrice: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#ff5722',
    marginRight: 8,
  },
  cartItemOldPrice: {
    fontSize: 13,
    color: colors.textMuted,
    textDecorationLine: 'line-through',
    marginLeft: 2,
  },
  cartItemQtyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  qtyBtn: {
    width: 28,
    height: 28,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.secondary,
  },
  cartItemQty: {
    fontSize: 15,
    fontWeight: 'bold',
    color: colors.textPrimary,
    marginHorizontal: 10,
    minWidth: 24,
    textAlign: 'center',
  },
  summaryBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  summaryVoucher: {
    fontSize: 15,
    color: colors.textPrimary,
    flex: 1,
  },
  summaryVoucherBtn: {
    fontSize: 14,
    color: '#ff5722',
    fontWeight: 'bold',
    marginLeft: 10,
  },
  summaryCoin: {
    fontSize: 15,
    color: colors.warning,
    flex: 1,
  },
});

export default CartScreenStyles; 