import { StyleSheet } from 'react-native';
import GlobalStyles, { colors } from './GlobalStyles';

const PaymentScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 10,
    backgroundColor: colors.secondary,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    zIndex: 30,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.textPrimary,
  },
  headerIcon: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addressCard: {
    backgroundColor: colors.card,
    borderRadius: 14,
    padding: 14,
    margin: 14,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  addressName: {
    fontSize: 15,
    color: colors.textPrimary,
    marginBottom: 2,
  },
  addressPhone: {
    color: colors.textMuted,
    fontSize: 13,
  },
  addressText: {
    color: colors.textSecondary,
    fontSize: 13,
    marginTop: 2,
  },
  shopCard: {
    backgroundColor: colors.card,
    borderRadius: 12,
    marginHorizontal: 14,
    marginBottom: 12,
    padding: 12,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 1,
  },
  shopTitle: {
    fontWeight: 'bold',
    fontSize: 15,
    color: colors.textPrimary,
    marginBottom: 8,
  },
  productRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 10,
  },
  productImage: {
    width: 60,
    height: 60,
    borderRadius: 8,
    backgroundColor: colors.lightGray,
  },
  productName: {
    fontSize: 14,
    fontWeight: 'bold',
    color: colors.textPrimary,
    marginBottom: 2,
  },
  productDesc: {
    fontSize: 13,
    color: colors.textSecondary,
    marginBottom: 2,
  },
  productPrice: {
    fontSize: 15,
    color: colors.primary,
    fontWeight: 'bold',
    marginRight: 8,
  },
  productOldPrice: {
    fontSize: 13,
    color: colors.textMuted,
    textDecorationLine: 'line-through',
    marginRight: 8,
  },
  productQty: {
    fontSize: 13,
    color: colors.textMuted,
    marginLeft: 8,
  },
  optionsCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    marginHorizontal: 14,
    marginBottom: 8,
    padding: 10,
    shadowColor: '#000',
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 1,
  },
  optionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  optionsText: {
    fontSize: 14,
    color: colors.textPrimary,
    flex: 1,
  },
  optionsPrice: {
    fontSize: 14,
    color: colors.primary,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  orderSummaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: 14,
    marginTop: 18,
    marginBottom: 8,
  },
  orderSummaryLabel: {
    fontSize: 15,
    color: colors.textPrimary,
  },
  orderSummaryValue: {
    fontSize: 16,
    color: colors.primary,
    fontWeight: 'bold',
  },
  fixedPayButtonContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colors.card,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingVertical: 10,
    paddingHorizontal: 14,
    zIndex: 100,
  },
  fixedPayButtonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  fixedPayButtonTotal: {
    fontSize: 18,
    color: colors.primary,
    fontWeight: 'bold',
    marginBottom: 2,
  },
  fixedPayButton: {
    backgroundColor: colors.primary,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fixedPayButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
});

export default PaymentScreenStyles;